global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "5.49.0.35:9093" 
rule_files:
  - alertrules.yml

scrape_configs:
- job_name: 'Host'
  file_sd_configs:
  - files:
    - 'targets.json'
